apiVersion: apps/v1
kind: Deployment
metadata:
  name: indio-site # <-- CORRIGÉ (pas d'underscore)
spec:
  selector:
    matchLabels:
      app: indio-site
  replicas: 1  
  template:  
    metadata:
      labels:
        app: indio-site
    spec:
      containers:
      - name: indio-site # <-- CORRIGÉ (pas d'underscore)
        image: nathang5991/indiogroup_internal_site:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: indio-site # <-- CORRIGÉ (pas d'underscore)
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: indio-site # <-- DOIT CORRESPONDRE AU LABEL DU DEPLOYMENT
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
